### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Kazachenko1998/Checker#1]
1. В первую очередь больше всего пугает глобальное статическое поле `gameMain`, которое дёргается из разных мест программы. Тут нужен рефакторинг.
2. Во многих местах дублирование кода. Классы `RulesForII`/`RulesForPeople`, `PieceForII`/`PieceForPeople` похожи на попытку отделить логику от интерфейса, однако они частично копируют код друг друга. Стоит использовать в них композицию вместо копирования.
3. Следующий код:
```java
if (moveType == MoveType.KILL) {
    if (turn == 1) new II(newFirstTurn, depth, pieceMy + 1, pieceOther, newRules);
    else
        new II(newFirstTurn, depth, pieceMy, pieceOther + 1, newRules);
} else if ( !rules.mustHackAllKing())
    new II(newFirstTurn, depth + 1, pieceMy, pieceOther, newRules);
```

выглядит совершенно безумно. Что вы пытались сделать? Вызвать конструктор уже созданного объекта? Как это должно работать? Фактически вы создаёте объекты и тут же про них забываете.
4. Местами есть огрехи в Code Style и форматировании.

**Comment by Kazachenko1998** [comment]
исправил первое замечание. теперь gameMain используется только в одном месте.
по поводу третьего замечания - это своего рода рекурсия или поиск в глубину... суть в том, что в конструкторе заключена вся логика бота, именно там идет оценка каждого хода.

**Comment by gagarski** [comment]
По поводу адской рекурсии. 

Наверно следует отделить создание объекта класса `II` и запуск выбора хода. В конструкторе просто инициализируйте поля, а рекурсивную логику запускайте в отдельном методе (например, `evaluate`). При создании "корневого" объекта `II` создавайте объект конструктором, и сразу вызывайте на нём `evaluate`.  Внутри объекта вместо рекурсивного вызова конструктора просто вызывайте этом метод. Поле `GameStart.turnHashMap ` лучше бы сделать нестатическим, а (хотя бы) передавать ссылку на него в `II`.
